export const EducationFormObject = [
    {
        id: "from",
        name: "From",
        type: "month",
        value: "",
        placeholder: "From",
        required: true,
    },
    {
        id: "to",
        name: "To",
        type: "month",
        value: "",
        placeholder: "To",
        required: true,
    },
    {
        id: "institution",
        name: "Institution",
        type: "text",
        value: "",
        placeholder: "Institution Name",
        required: true,
    },
    {
        id: "subject",
        name: "Subject",
        type: "text",
        value: "",
        placeholder: "Subject of studying",
    },
    {
        id: "description",
        name: "Description",
        type: "textarea",
        value: "",
        placeholder: "Description",
    },
];
