export const PersonalInfo = [
    {
        id: "displayName",
        label: "*Display Name",
        type: "text",
        placeholder: "Enter your display name",
        value: "",
        required: true,
    },
    {
        id: "firstName",
        label: "*First Name",
        type: "text",
        placeholder: "Enter your first name",
        value: "",
        required: true,
    },
    {
        id: "secondName",
        label: "Second Name",
        type: "text",
        placeholder: "Enter your second name",
        value: "",
    },
    {
        id: "lastName",
        label: "*Last Name",
        type: "text",
        placeholder: "Enter your last name",
        value: "",
        required: true,
    },
    {
        id: "email",
        label: "*Email",
        type: "email",
        placeholder: "Enter your email",
        value: "",
        required: true,
    },
    {
        id: "phoneNumber",
        label: "*Phone Number",
        type: "tel",
        placeholder: "Enter your phone number",
        value: "",
        required: true,
    },
    {
        id: "address",
        label: "Address",
        type: "text",
        placeholder: "Enter your address",
        value: "",
    },
    {
        id: "city",
        label: "City",
        type: "text",
        placeholder: "Enter your city",
        value: "",
    },
    {
        id: "country",
        label: "*Country",
        type: "text",
        placeholder: "Enter your country",
        value: "",
        required: true,
    },
    {
        id: "birthday",
        label: "*Birthday",
        type: "date",
        placeholder: "Enter your birthday",
        value: "",
        required: true,
    },
    {
        id: "nationality",
        label: "Nationality",
        type: "text",
        placeholder: "Enter your nationality",
        value: "",
    },
];
